// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/dnlopes/overseer/internal/core/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSwarmDescriptorWriter creates a new instance of MockSwarmDescriptorWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSwarmDescriptorWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSwarmDescriptorWriter {
	mock := &MockSwarmDescriptorWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSwarmDescriptorWriter is an autogenerated mock type for the SwarmDescriptorWriter type
type MockSwarmDescriptorWriter struct {
	mock.Mock
}

type MockSwarmDescriptorWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSwarmDescriptorWriter) EXPECT() *MockSwarmDescriptorWriter_Expecter {
	return &MockSwarmDescriptorWriter_Expecter{mock: &_m.Mock}
}

// Write provides a mock function for the type MockSwarmDescriptorWriter
func (_mock *MockSwarmDescriptorWriter) Write(ctx context.Context, desc domain.SwarmDescriptor) error {
	ret := _mock.Called(ctx, desc)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.SwarmDescriptor) error); ok {
		r0 = returnFunc(ctx, desc)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSwarmDescriptorWriter_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type MockSwarmDescriptorWriter_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - ctx context.Context
//   - desc domain.SwarmDescriptor
func (_e *MockSwarmDescriptorWriter_Expecter) Write(ctx interface{}, desc interface{}) *MockSwarmDescriptorWriter_Write_Call {
	return &MockSwarmDescriptorWriter_Write_Call{Call: _e.mock.On("Write", ctx, desc)}
}

func (_c *MockSwarmDescriptorWriter_Write_Call) Run(run func(ctx context.Context, desc domain.SwarmDescriptor)) *MockSwarmDescriptorWriter_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.SwarmDescriptor
		if args[1] != nil {
			arg1 = args[1].(domain.SwarmDescriptor)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSwarmDescriptorWriter_Write_Call) Return(err error) *MockSwarmDescriptorWriter_Write_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSwarmDescriptorWriter_Write_Call) RunAndReturn(run func(ctx context.Context, desc domain.SwarmDescriptor) error) *MockSwarmDescriptorWriter_Write_Call {
	_c.Call.Return(run)
	return _c
}
