// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/dnlopes/overseer/internal/core/domain"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSwarmBoardRepository creates a new instance of MockSwarmBoardRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSwarmBoardRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSwarmBoardRepository {
	mock := &MockSwarmBoardRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSwarmBoardRepository is an autogenerated mock type for the SwarmBoardRepository type
type MockSwarmBoardRepository struct {
	mock.Mock
}

type MockSwarmBoardRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSwarmBoardRepository) EXPECT() *MockSwarmBoardRepository_Expecter {
	return &MockSwarmBoardRepository_Expecter{mock: &_m.Mock}
}

// Append provides a mock function for the type MockSwarmBoardRepository
func (_mock *MockSwarmBoardRepository) Append(ctx context.Context, msg domain.SwarmMessage) (domain.SwarmMessage, error) {
	ret := _mock.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for Append")
	}

	var r0 domain.SwarmMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.SwarmMessage) (domain.SwarmMessage, error)); ok {
		return returnFunc(ctx, msg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.SwarmMessage) domain.SwarmMessage); ok {
		r0 = returnFunc(ctx, msg)
	} else {
		r0 = ret.Get(0).(domain.SwarmMessage)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.SwarmMessage) error); ok {
		r1 = returnFunc(ctx, msg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSwarmBoardRepository_Append_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Append'
type MockSwarmBoardRepository_Append_Call struct {
	*mock.Call
}

// Append is a helper method to define mock.On call
//   - ctx context.Context
//   - msg domain.SwarmMessage
func (_e *MockSwarmBoardRepository_Expecter) Append(ctx interface{}, msg interface{}) *MockSwarmBoardRepository_Append_Call {
	return &MockSwarmBoardRepository_Append_Call{Call: _e.mock.On("Append", ctx, msg)}
}

func (_c *MockSwarmBoardRepository_Append_Call) Run(run func(ctx context.Context, msg domain.SwarmMessage)) *MockSwarmBoardRepository_Append_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.SwarmMessage
		if args[1] != nil {
			arg1 = args[1].(domain.SwarmMessage)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSwarmBoardRepository_Append_Call) Return(swarmMessage domain.SwarmMessage, err error) *MockSwarmBoardRepository_Append_Call {
	_c.Call.Return(swarmMessage, err)
	return _c
}

func (_c *MockSwarmBoardRepository_Append_Call) RunAndReturn(run func(ctx context.Context, msg domain.SwarmMessage) (domain.SwarmMessage, error)) *MockSwarmBoardRepository_Append_Call {
	_c.Call.Return(run)
	return _c
}

// Count provides a mock function for the type MockSwarmBoardRepository
func (_mock *MockSwarmBoardRepository) Count(ctx context.Context, sessionID uuid.UUID) (int, error) {
	ret := _mock.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int, error)); ok {
		return returnFunc(ctx, sessionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) int); ok {
		r0 = returnFunc(ctx, sessionID)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSwarmBoardRepository_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockSwarmBoardRepository_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID uuid.UUID
func (_e *MockSwarmBoardRepository_Expecter) Count(ctx interface{}, sessionID interface{}) *MockSwarmBoardRepository_Count_Call {
	return &MockSwarmBoardRepository_Count_Call{Call: _e.mock.On("Count", ctx, sessionID)}
}

func (_c *MockSwarmBoardRepository_Count_Call) Run(run func(ctx context.Context, sessionID uuid.UUID)) *MockSwarmBoardRepository_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSwarmBoardRepository_Count_Call) Return(n int, err error) *MockSwarmBoardRepository_Count_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockSwarmBoardRepository_Count_Call) RunAndReturn(run func(ctx context.Context, sessionID uuid.UUID) (int, error)) *MockSwarmBoardRepository_Count_Call {
	_c.Call.Return(run)
	return _c
}

// ListSince provides a mock function for the type MockSwarmBoardRepository
func (_mock *MockSwarmBoardRepository) ListSince(ctx context.Context, sessionID uuid.UUID, since int) ([]domain.SwarmMessage, error) {
	ret := _mock.Called(ctx, sessionID, since)

	if len(ret) == 0 {
		panic("no return value specified for ListSince")
	}

	var r0 []domain.SwarmMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) ([]domain.SwarmMessage, error)); ok {
		return returnFunc(ctx, sessionID, since)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) []domain.SwarmMessage); ok {
		r0 = returnFunc(ctx, sessionID, since)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.SwarmMessage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, int) error); ok {
		r1 = returnFunc(ctx, sessionID, since)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSwarmBoardRepository_ListSince_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSince'
type MockSwarmBoardRepository_ListSince_Call struct {
	*mock.Call
}

// ListSince is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID uuid.UUID
//   - since int
func (_e *MockSwarmBoardRepository_Expecter) ListSince(ctx interface{}, sessionID interface{}, since interface{}) *MockSwarmBoardRepository_ListSince_Call {
	return &MockSwarmBoardRepository_ListSince_Call{Call: _e.mock.On("ListSince", ctx, sessionID, since)}
}

func (_c *MockSwarmBoardRepository_ListSince_Call) Run(run func(ctx context.Context, sessionID uuid.UUID, since int)) *MockSwarmBoardRepository_ListSince_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSwarmBoardRepository_ListSince_Call) Return(swarmMessages []domain.SwarmMessage, err error) *MockSwarmBoardRepository_ListSince_Call {
	_c.Call.Return(swarmMessages, err)
	return _c
}

func (_c *MockSwarmBoardRepository_ListSince_Call) RunAndReturn(run func(ctx context.Context, sessionID uuid.UUID, since int) ([]domain.SwarmMessage, error)) *MockSwarmBoardRepository_ListSince_Call {
	_c.Call.Return(run)
	return _c
}

// Purge provides a mock function for the type MockSwarmBoardRepository
func (_mock *MockSwarmBoardRepository) Purge(ctx context.Context, sessionID uuid.UUID) error {
	ret := _mock.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for Purge")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, sessionID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSwarmBoardRepository_Purge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Purge'
type MockSwarmBoardRepository_Purge_Call struct {
	*mock.Call
}

// Purge is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID uuid.UUID
func (_e *MockSwarmBoardRepository_Expecter) Purge(ctx interface{}, sessionID interface{}) *MockSwarmBoardRepository_Purge_Call {
	return &MockSwarmBoardRepository_Purge_Call{Call: _e.mock.On("Purge", ctx, sessionID)}
}

func (_c *MockSwarmBoardRepository_Purge_Call) Run(run func(ctx context.Context, sessionID uuid.UUID)) *MockSwarmBoardRepository_Purge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSwarmBoardRepository_Purge_Call) Return(err error) *MockSwarmBoardRepository_Purge_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSwarmBoardRepository_Purge_Call) RunAndReturn(run func(ctx context.Context, sessionID uuid.UUID) error) *MockSwarmBoardRepository_Purge_Call {
	_c.Call.Return(run)
	return _c
}
