// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockGitAdapter creates a new instance of MockGitAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGitAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGitAdapter {
	mock := &MockGitAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGitAdapter is an autogenerated mock type for the GitAdapter type
type MockGitAdapter struct {
	mock.Mock
}

type MockGitAdapter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGitAdapter) EXPECT() *MockGitAdapter_Expecter {
	return &MockGitAdapter_Expecter{mock: &_m.Mock}
}

// CreateWorktree provides a mock function for the type MockGitAdapter
func (_mock *MockGitAdapter) CreateWorktree(ctx context.Context, repoPath string, baseBranch string, featureBranch string, worktreePath string) error {
	ret := _mock.Called(ctx, repoPath, baseBranch, featureBranch, worktreePath)

	if len(ret) == 0 {
		panic("no return value specified for CreateWorktree")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) error); ok {
		r0 = returnFunc(ctx, repoPath, baseBranch, featureBranch, worktreePath)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGitAdapter_CreateWorktree_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWorktree'
type MockGitAdapter_CreateWorktree_Call struct {
	*mock.Call
}

// CreateWorktree is a helper method to define mock.On call
//   - ctx context.Context
//   - repoPath string
//   - baseBranch string
//   - featureBranch string
//   - worktreePath string
func (_e *MockGitAdapter_Expecter) CreateWorktree(ctx interface{}, repoPath interface{}, baseBranch interface{}, featureBranch interface{}, worktreePath interface{}) *MockGitAdapter_CreateWorktree_Call {
	return &MockGitAdapter_CreateWorktree_Call{Call: _e.mock.On("CreateWorktree", ctx, repoPath, baseBranch, featureBranch, worktreePath)}
}

func (_c *MockGitAdapter_CreateWorktree_Call) Run(run func(ctx context.Context, repoPath string, baseBranch string, featureBranch string, worktreePath string)) *MockGitAdapter_CreateWorktree_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockGitAdapter_CreateWorktree_Call) Return(err error) *MockGitAdapter_CreateWorktree_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGitAdapter_CreateWorktree_Call) RunAndReturn(run func(ctx context.Context, repoPath string, baseBranch string, featureBranch string, worktreePath string) error) *MockGitAdapter_CreateWorktree_Call {
	_c.Call.Return(run)
	return _c
}

// GetDefaultBranch provides a mock function for the type MockGitAdapter
func (_mock *MockGitAdapter) GetDefaultBranch(ctx context.Context, repoPath string) (string, error) {
	ret := _mock.Called(ctx, repoPath)

	if len(ret) == 0 {
		panic("no return value specified for GetDefaultBranch")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, repoPath)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, repoPath)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, repoPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGitAdapter_GetDefaultBranch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDefaultBranch'
type MockGitAdapter_GetDefaultBranch_Call struct {
	*mock.Call
}

// GetDefaultBranch is a helper method to define mock.On call
//   - ctx context.Context
//   - repoPath string
func (_e *MockGitAdapter_Expecter) GetDefaultBranch(ctx interface{}, repoPath interface{}) *MockGitAdapter_GetDefaultBranch_Call {
	return &MockGitAdapter_GetDefaultBranch_Call{Call: _e.mock.On("GetDefaultBranch", ctx, repoPath)}
}

func (_c *MockGitAdapter_GetDefaultBranch_Call) Run(run func(ctx context.Context, repoPath string)) *MockGitAdapter_GetDefaultBranch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGitAdapter_GetDefaultBranch_Call) Return(s string, err error) *MockGitAdapter_GetDefaultBranch_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockGitAdapter_GetDefaultBranch_Call) RunAndReturn(run func(ctx context.Context, repoPath string) (string, error)) *MockGitAdapter_GetDefaultBranch_Call {
	_c.Call.Return(run)
	return _c
}

// IsGitRepo provides a mock function for the type MockGitAdapter
func (_mock *MockGitAdapter) IsGitRepo(ctx context.Context, path string) error {
	ret := _mock.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for IsGitRepo")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, path)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGitAdapter_IsGitRepo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsGitRepo'
type MockGitAdapter_IsGitRepo_Call struct {
	*mock.Call
}

// IsGitRepo is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
func (_e *MockGitAdapter_Expecter) IsGitRepo(ctx interface{}, path interface{}) *MockGitAdapter_IsGitRepo_Call {
	return &MockGitAdapter_IsGitRepo_Call{Call: _e.mock.On("IsGitRepo", ctx, path)}
}

func (_c *MockGitAdapter_IsGitRepo_Call) Run(run func(ctx context.Context, path string)) *MockGitAdapter_IsGitRepo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGitAdapter_IsGitRepo_Call) Return(err error) *MockGitAdapter_IsGitRepo_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGitAdapter_IsGitRepo_Call) RunAndReturn(run func(ctx context.Context, path string) error) *MockGitAdapter_IsGitRepo_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveWorktree provides a mock function for the type MockGitAdapter
func (_mock *MockGitAdapter) RemoveWorktree(ctx context.Context, repoPath string, worktreePath string) error {
	ret := _mock.Called(ctx, repoPath, worktreePath)

	if len(ret) == 0 {
		panic("no return value specified for RemoveWorktree")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, repoPath, worktreePath)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGitAdapter_RemoveWorktree_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveWorktree'
type MockGitAdapter_RemoveWorktree_Call struct {
	*mock.Call
}

// RemoveWorktree is a helper method to define mock.On call
//   - ctx context.Context
//   - repoPath string
//   - worktreePath string
func (_e *MockGitAdapter_Expecter) RemoveWorktree(ctx interface{}, repoPath interface{}, worktreePath interface{}) *MockGitAdapter_RemoveWorktree_Call {
	return &MockGitAdapter_RemoveWorktree_Call{Call: _e.mock.On("RemoveWorktree", ctx, repoPath, worktreePath)}
}

func (_c *MockGitAdapter_RemoveWorktree_Call) Run(run func(ctx context.Context, repoPath string, worktreePath string)) *MockGitAdapter_RemoveWorktree_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGitAdapter_RemoveWorktree_Call) Return(err error) *MockGitAdapter_RemoveWorktree_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGitAdapter_RemoveWorktree_Call) RunAndReturn(run func(ctx context.Context, repoPath string, worktreePath string) error) *MockGitAdapter_RemoveWorktree_Call {
	_c.Call.Return(run)
	return _c
}
